### ISSUE TITLE
The_Lambda_parameters notebook

### ISSUE THREAD

**Issue by XJtsinghua1992** [r2stanton/pyrovskite#3]
Hi, 
I am sorry that I don't find The_Lambda_parameters.ipynb notebook in the package. Could you please upload it or share it with me?

Thank you very much

**Comment by r2stanton** [comment]
Ah great point, thanks for letting me know it's not up here! I should be able to get it uploaded by the weekend.

In the meanwhile just in case you need it quickly, the overall idea is this:
Lambda3 describes diagonal B-cation displacements along all 3 directions of the octahedra.
Lambda2 describes the largest diagonal B-cation displacements along one of the three planes of the octahedra.

Then in terms of usage, if you use `compute_lambda(..., return_type = 'octahedra_lambda')` the returned signature will be:
`octahedra_lambda3, octahedra_lambda2` where each of these is a np.ndarray containing the Lambda3, Lambda2 values for each individual octahedra.

`compute_lambda(..., return_type = 'lambda')` will do the same as above, but instead of np.ndarrays, it will simply return the average Lambda3, Lambda2 across all octahedra in the system.

And finally `compute_lambda(..., return_type = 'both')` returns both of the above with the return signature of:
`each_Lambda3, each_Lambda2, average_Lambda3, average_Lambda2`.

In terms of the parameters themselves for a more detailed description check out:
 https://doi.org/10.1063/5.0159407

Hope this helps in the meantime, and thanks for bringing up that the notebook is currently missing!

**Comment by XJtsinghua1992** [comment]
Hi,

It seems there is no The_Lambda_parameters.ipynb notebook in the package. I tried the following codes, but it failed. Could you help check it? Thank you.

each_Lambda3, each_Lambda2, average_Lambda3, average_Lambda2 = opt.compute_lambda(return_type='both')
print(F"each_Lambda3:{each_Lambda3}")
print(F"each_Lambda2:{each_Lambda2}")
print(F"average_Lambda3:{average_Lambda3}")
print(F"average_Lambda2:{average_Lambda2}")

**Comment by r2stanton** [comment]
Hi, sorry for the delay but the notebook is up now!

Yes what you have there is correct, so if you have some `Perovskite` object `perov`, then you can do this: 
```oct_lambda_3_both, oct_lambda_2_both, lambda_3_both, lambda_2_both = perov.compute_lambda(return_type = 'both')```

Then the first two would be the individual values by octahedra, and the final two would be the averaged ones.
